bvt_allowlist: add login_UserPolicyKeys
Without this changes to this test fail the following presubmit:

  __main__.ControlFileCheckerError: login_UserPolicyKeys not in the BVT
  allowlist. New BVT tests should be written in Tast, not in Autotest.
  See: https://groups.google.com/a/chromium.org/d/topic/chromium-os-dev/zH1nO7OjJ2M/discussion

BUG=b:182921454
TEST=none

Change-Id: I8bc32a8cd4a730623e481e7dc709f1a2a72cee4e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2773946
Reviewed-by: David Haddock <dhaddock@chromium.org>
Reviewed-by: Ross Zwisler <zwisler@google.com>
Reviewed-by: Roman Sorokin [CET] <rsorokin@chromium.org>
Commit-Queue: Ross Zwisler <zwisler@google.com>
Tested-by: Ross Zwisler <zwisler@google.com>
Auto-Submit: Ross Zwisler <zwisler@google.com>