Fix lacros control retries error
https://ci.chromium.org/ui/p/chromeos/builders/testplatform/cros_test_platform/b8783916890443321425/overview
"/usr/local/autotest/autotest_lib/server/site_tests/tast/tast.py", line 912, in _run_tests
    args.append('-retries=%d' % self._retries)
TypeError: %d format: a number is required, not str

We're passing it as int:
"retries=2 exe_rel_path=out/Release/chrome tast_expr_file=out/Release/bin/lacros_all_tast_tests.filter tast_expr_key=default max_run_sec=5400 shard_index=0 total_shards=1"
But it's parsed as str. So this fix would make it as int.

Bug: b/278095185
Change-Id: I508e7844c5d78bf8b29363e1a0151877067a5f0a
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/4422975
Reviewed-by: Xinan Lin <linxinan@chromium.org>
Reviewed-by: Derek Beckett <dbeckett@chromium.org>
Tested-by: Sven Zheng <svenzheng@chromium.org>
Commit-Queue: Sven Zheng <svenzheng@chromium.org>