bluetooth: restart bluetoothd by restart_services
This patch uses restart_services() to replace
self.test_stop_bluetoothd() and self.test_start_bluetoothd() since
the latter will lead to a dbus error with an unknown reason:

  Exception: RuntimeError: To make asynchronous calls, receive
  signals or export objects, D-Bus connections must be attached
  to a main loop by passing mainloop=... to the constructor or
  calling dbus.set_default_main_loop(...)

As a work around, the restart_services() is employed like
controlling other services such as ui, cras, etc.

BUG=b:252868124,b:254581792
TEST=The following tests passed.
- all tests in bluetooth_AdapterQRHealth including qr_check_states_test
- all tests in bluetooth_AdapterSRHealth

Change-Id: I0093020109a32f1f5d06de8a4daa590f07b48b65
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/3971139
Commit-Queue: Shyh-In Hwang <josephsih@chromium.org>
Reviewed-by: Ying Hsu <yinghsu@chromium.org>
Tested-by: Shyh-In Hwang <josephsih@chromium.org>