network_EthernetStressPlug: enable CDC NCM support
... FAIL    network_EthernetStressPlug...
Unhandled KeyError: KeyError('Advertised link modes',)

  Traceback (most recent call last):
    File "/usr/local/autotest/tests/network_EthernetStressPlug/network_EthernetStressPlug.py", line 488, in run_once
      self.dongle = self.GetDongle()
    File "/usr/local/autotest/tests/network_EthernetStressPlug/network_EthernetStressPlug.py", line 481, in GetDongle
      max_link = ethtool_dict['Advertised link modes'][-1]
  KeyError: 'Advertised link modes'

CDC NCM ethtool output is too short:
localhost ~ # ethtool --version
ethtool version 4.13
localhost ~ # ethtool eth0
Settings for eth0:
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes

This test just needs to know about link state (which is reported).

FTR, the kernel I generated the output on (v5.4 or v5.10) is missing CDC NCM
changes from April 2021 (which landed upstream in v5.13):
   https://lkml.org/lkml/2021/4/6/1266

Since this test worked fine with cdc_ncm and cdc_ether when I submitted
this previous change:
    https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2822297

I'm going to assume I had the missing changes in my local tree then.
Backporting those now:
	https://chromium-review.googlesource.com/q/hashtag:usbnet-backports-2022q1+(status:open%20OR%20status:merged)

BUG=none
TEST=test_that --py_version 3 100.90.25.195 network_EthernetStressPlug
   (using 2.5Gbps USB dongle; RTL8156)

Change-Id: I76632a7bbbe8f65780de34cf8bbb9aa0edc8ef25
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/3360271
Tested-by: Grant Grundler <grundler@chromium.org>
Reviewed-by: Greg Edelston <gredelston@google.com>
Reviewed-by: Grant Grundler <grundler@chromium.org>
Auto-Submit: Grant Grundler <grundler@chromium.org>
Commit-Queue: Grant Grundler <grundler@chromium.org>