platform_KernelErrorPaths.EXCEPTION: update for arm64 PAN
With ARM64_SW_TTBR0_PAN (present on v4.19+ kernels), lkdtm EXCEPTIONs
(dereferencing a 0 pointer) hit a Privileged Access Never exception
instead of the traditional "kernel NULL pointer dereference" exception
type. Support both.

BUG=b:191493568
TEST=`platform_KernelErrorPaths.EXCEPTION` on kevin-kernelnext

Change-Id: I7841f0255c73537302c66c22409e5b48766f8d84
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/3111650
Reviewed-by: Stephen Boyd <swboyd@chromium.org>
Commit-Queue: Brian Norris <briannorris@chromium.org>
Tested-by: Brian Norris <briannorris@chromium.org>