[Autotest][Py3] Update error.py to support Python3
locals.items() in python2 is a list, where in 3 its a generator.
It needs to be list casted in python3, as its being modified in place.
Example err:
RuntimeError: dictionary changed size during iteration

File "/mnt/host/source/src/third_party/autotest/files/autotest_lib/client/common_lib/error.py", line 517, in <module>
    for _name, _thing in (locals().items()):
RuntimeError: dictionary changed size during iteration

BUG=chromium:990593
TEST=dummy_Pass (python2 and 3)

Change-Id: I2b8a6069e6464b972e4bdcfdec7552eb177885c3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2546845
Reviewed-by: Prathmesh Prabhu <pprabhu@google.com>
Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>
Tested-by: Derek Beckett <dbeckett@chromium.org>
Auto-Submit: Derek Beckett <dbeckett@chromium.org>
Commit-Queue: Gregory Nisbet <gregorynisbet@google.com>