autotest: Sync disk after installing autotest.
If a test performs a reset immediately after installing autotest,
some of the python files can become empty afterwards, since they
weren't really written yet.  This causes failures like the following:

  AutotestRunError: execute_section 0 failed to return anything

Syncing the disk fixes this, ensuring that the files aren't empty.

BUG=b:140625492
TEST=Run platform_ServoPowerStateController_USBPluggedin for multiple iterations.

Change-Id: I629f79cd6d0a3db6aa7554db6de6e1e13e9aa2b1
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2088198
Commit-Queue: Dana Goyette <dgoyette@chromium.org>
Tested-by: Dana Goyette <dgoyette@chromium.org>
Reviewed-by: Shelley Chen <shchen@chromium.org>