autotest: client: Allow rootdev at device lookup to fail
rootdev can be invoked for files who do not have backing devices
(over tmpfs for instance). rootdev supports it but report an error:

rootdev -s -d  /tmp/ramdisk/test ; echo $?
unable to find match
1
rootdev -s -d  /tmp/ramdisk/test 2>/dev/null ; echo $?
1

Allow rootdev to fail, report an empty device.

BUG=b:241137765, b:258894894
TEST=Without fix. `test_that <IP> hardware_RamFio` fails with:
[  FAILED  ]
ERROR: Command <rootdev -s -d "/tmp/ramdisk/test_file"> failed, rc=1, Command returned non-zero exit status
After fix, hardware_RamFio passes.

Fixes: 596d92fb9b2 ("autotest: client: Use rootdev to lookup device for filename")
Change-Id: I970096fd3f20f5ea9e90cd9e370894c61c068fc7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/4277924
Tested-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-by: Puthikorn Voravootivat <puthik@chromium.org>
Reviewed-by: Sarthak Kukreti <sarthakkukreti@google.com>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>