tradefed_test: Add missing suite_name argument
The creation of the BundleSpecification object in
_get_bundle_specification() is missing the named argument |suite_name|,
causing a crash when using the following command:

(inside)
$ test_that --autotest_dir ~/chromiumos/src/third_party/autotest/files <IP> \
--args="module=CtsViewTestCases test=android.view.cts.ASurfaceControlBackPressureTest#testSurfaceTransaction_setEnableBackPressure retry=0 revision=13_r8" \
cheets_CTS_T.tradefed-run-test
...
ERROR: Unhandled TypeError: __init__() missing 1 required positional argument: 'suite_name'

Add the named argument to prevent the crash.

BUG=b:349185986
TEST=test_that --autotest_dir ~/chromiumos/src/third_party/autotest/files <IP> \
--args="module=CtsViewTestCases test=android.view.cts.ASurfaceControlBackPressureTest#testSurfaceTransaction_setEnableBackPressure retry=0 revision=13_r8" \
cheets_CTS_T.tradefed-run-test

Change-Id: Ie69ec0af3eabc81fdb12a0dc5b4a8cf4f409f997
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/5719381
Tested-by: Tim Van Patten <timvp@google.com>
Commit-Queue: Kazuhiro Inaba <kinaba@chromium.org>
Commit-Queue: Tim Van Patten <timvp@google.com>
Reviewed-by: Shao-Chuan Lee <shaochuan@chromium.org>