power_CPUFreq: Give better errors if test_cores_in_parallel() won't work
Right now if test_cores_in_series() fails on a device where not all
CPUs have the same frequencies (like any modern arm64 device), it's
super confusing. When test_cores_in_series() fails then we'll fall
back to test_cores_in_parallel() which was just never intended to run
on a device where not all CPUs were equal.

Let's make it less confusing. We'll now detect the problem and print
out which CPUs we noticed had different frequencies. We'll also make
it more obvious that the fact that the "parallel" test fails wasn't
really the initial problem by saying that we can't
"fallback". Hopefully that will help someone realize that the actual
bug was in test_cores_in_series() which needs to work on any system
where the CPUs aren't all alike.

After this patch if I end up in test_cores_in_parallel() on a lazor
device, I see:

ERROR: Can't fallback to parallel test: cpu5 / cpu7 differ: [652800,
825600, 979200, 1113600, 1267200, 1555200, 1708800, 1843200, 1900800,
1996800, 2112000] / [300000, 576000, 768000, 1017600, 1248000,
1324800, 1516800, 1612800, 1708800, 1804800]

BUG=b:173229974
TEST=test_that ${DUT} power_CPUFreq --fast --iterations=100

Change-Id: I118cca7891d4d96d4198ff7d61dd56c8da8b9eab
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2904711
Tested-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Stephen Boyd <swboyd@chromium.org>
Commit-Queue: Douglas Anderson <dianders@chromium.org>